"""add_inward_module_tables

Revision ID: c0b6c98a6f2d
Revises: 9014f72e9f0c
Create Date: 2026-06-28 22:20:26.377624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0b6c98a6f2d'
down_revision: Union[str, None] = '9014f72e9f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The initial migration (9014f72e9f0c) deferred Phase 1+ enum creation.
    # Create the 5 enum types needed by inward module tables now.
    # PostgreSQL does not support CREATE TYPE IF NOT EXISTS, so use DO blocks.
    op.execute(
        "DO $$ BEGIN "
        "CREATE TYPE counter_type_enum AS ENUM ('outward_box', 'inscan_number', 'inward_box'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; "
        "END $$"
    )
    op.execute(
        "DO $$ BEGIN "
        "CREATE TYPE ledger_source_type_enum AS ENUM "
        "('inward_submission', 'outward_scan', 'outward_scan_deletion', 'inward_scan_deletion'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; "
        "END $$"
    )
    op.execute(
        "DO $$ BEGIN "
        "CREATE TYPE inward_box_status_enum AS ENUM "
        "('scanning', 'pending_verification', 'completed'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; "
        "END $$"
    )
    op.execute(
        "DO $$ BEGIN "
        "CREATE TYPE inward_reference_status_enum AS ENUM ('open', 'completed'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; "
        "END $$"
    )
    op.execute(
        "DO $$ BEGIN "
        "CREATE TYPE inward_code_type_enum AS ENUM ('ean', 'style_code'); "
        "EXCEPTION WHEN duplicate_object THEN NULL; "
        "END $$"
    )

    # --- autogenerated CREATE TABLE statements follow here (do not remove them) ---
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counter_type', postgresql.ENUM('outward_box', 'inscan_number', 'inward_box', name='counter_type_enum', create_type=False), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.Text(), nullable=False),
    sa.Column('date_key', sa.Text(), server_default='', nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('counter_type', 'organisation_id', 'customer_code', 'date_key', name='uq_counters_key')
    )
    op.create_table('inventory_ledger_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.Text(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('source_type', postgresql.ENUM('inward_submission', 'outward_scan', 'outward_scan_deletion', 'inward_scan_deletion', name='ledger_source_type_enum', create_type=False), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_org_ean', 'inventory_ledger_entries', ['organisation_id', 'ean'], unique=False)
    op.create_table('inward_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Text(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('scanning', 'pending_verification', 'completed', name='inward_box_status_enum', create_type=False), nullable=False),
    sa.Column('physical_qty', sa.Integer(), nullable=True),
    sa.Column('scanned_qty', sa.Integer(), nullable=False),
    sa.Column('inscan_number', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('box_id')
    )
    op.create_index('idx_inward_boxes_org_status', 'inward_boxes', ['organisation_id', 'status'], unique=False)
    op.create_table('inward_pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'completed', name='inward_reference_status_enum', create_type=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'po_number', name='uq_inward_pos_org_po')
    )
    op.create_table('inward_po_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inward_po_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('packed_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inward_po_id'], ['inward_pos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inward_po_lines_ean_org', 'inward_po_lines', ['organisation_id', 'ean'], unique=False)
    op.create_table('inward_scans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('inward_box_id', sa.Integer(), nullable=False),
    sa.Column('inward_po_line_id', sa.Integer(), nullable=True),
    sa.Column('ean', sa.Text(), nullable=False),
    sa.Column('code_type', postgresql.ENUM('ean', 'style_code', name='inward_code_type_enum', create_type=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inward_box_id'], ['inward_boxes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inward_po_line_id'], ['inward_po_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop tables in reverse dependency order.
    op.drop_table("inventory_ledger_entries")
    op.drop_table("inward_scans")
    op.drop_table("inward_boxes")
    op.drop_table("inward_po_lines")
    op.drop_table("inward_pos")
    op.drop_table("counters")

    # Drop enum types created in this migration (tables referencing them are already gone).
    op.execute("DROP TYPE IF EXISTS inward_code_type_enum")
    op.execute("DROP TYPE IF EXISTS inward_reference_status_enum")
    op.execute("DROP TYPE IF EXISTS inward_box_status_enum")
    op.execute("DROP TYPE IF EXISTS ledger_source_type_enum")
    op.execute("DROP TYPE IF EXISTS counter_type_enum")
